spring:
  datasource:
    url: jdbc:mysql://182.61.52.221:3306/LioveeCommunity?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: '!aA154678794'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  application:
    name: liovee-community-j

server:
  port: 9001
  servlet:
    context-path: /sysin

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

